### ISSUE TITLE
Multi-line Notes Input on Edit Runner View

### ISSUE THREAD

**Issue by cartpauj** [barcradio/ultra-tracker#121]
It would be nice if the notes input on the edit runner view had a multi-lined input field rather than a single line.

I'm not familiar enough with Electron to say the right terminology, but in HTML it would be a `textarea` vs a `text` input type.

Perhaps you could ignore input from the enter key and strip out any new line characters during apply to ensure the CSV doesn't have any new lines in that field.

**Comment by derethil** [comment]
Closed by MR #145
