### ISSUE TITLE
Auto-replace commas in notes

### ISSUE THREAD

**Issue by cartpauj** [barcradio/ultra-tracker#122]
When we're in the busy time (lots of runners in and out), we need to do things quickly.

Editing a runner, and accidentally typing a comma, could really slow us down when we click apply, and suddenly there's an error blocking us from moving on to the next bib that just came through and needs to be logged.

It would be great if the software just auto-converted any invalid characters such as a comma to some other acceptable character like a semi-colon.

**Comment by derethil** [comment]
Closed by MR #145
