### ISSUE TITLE
Confirmation messages should disappear faster

### ISSUE THREAD

**Issue by cartpauj** [barcradio/ultra-tracker#125]
It might be nice if the confirmation messages could disappear faster, or maybe be less intrusive.

In one case I was trying to quickly delete a couple of duplicate entries (may not be practical in real life, IDK), but the message was blocking the delete button: https://cdn.zappy.app/fb015f949fcefca1c0dedb3b732f5183.png

**Comment by derethil** [comment]
Closed by #153, took the approach of allowing users to click notifications to dismiss in case they are blocking something. If notifications are still too intrusive and need to disappear faster we can look into it again.
