### ISSUE TITLE
Button to open the CSV export directory

### ISSUE THREAD

**Issue by cartpauj** [barcradio/ultra-tracker#126]
Next to the export button, it would be cool if there was another button to "Open Export Folder". When clicked, it would open the folder where the exports are being stored.

**Comment by rleikis** [comment]
[commit: feat(export): added button for opening export directory
](https://github.com/barcradio/ultra-tracker/commit/598842d2112664437f7c92edeb14a6ccc6b016ff)
forgot to create branch
