### ISSUE TITLE
Help View

### ISSUE THREAD

**Issue by rleikis** [barcradio/ultra-tracker#20]
- [ ] Help system within the application

Requirements
- User must be able to access help about features within the application
  - look at doxygen or similar html documentation

**Comment by Tibbs327** [comment]
Format looks great, need a couple of updates, but those can wait for a bit. Colored text for Hard database warnings worked, but need to clarify that it correlates to the buttons on the DB tab, (for some reason it wasn't apparent to me, I was looking for other colored references on the help page)
