### ISSUE TITLE
DNS / DNF Export

### ISSUE THREAD

**Issue by rleikis** [barcradio/ultra-tracker#70]
- [x] Export DNS File
- [x] Export DNF File

Requirements
- Start line user must be able to export DNS entries
- Station user may export DNS list (but doesn't make a lot of sense, just exports what they already imported
- User must be able to export DNF entries that occurred at your station

**Comment by Tibbs327** [comment]
Note from Data about DNS/DNF lists. They are currently being generated from ADILAS web interface, which is where the file format is established at in the example files we had. The process is typically like this; Thursday evening Cody generates the list from his full registration list of athletes to show those that are expected to start the next morning. That list goes to data team and adilias, There is a QR code (google sheet login) that start line runs friday morning. The DNS list is created after manually performing a bulk start, unchecking the runners that didn't check in, then export. (aid 0 start times get populated at that point) 

Description of it from Shirley at data team:
"Yes, upon request the online software generates DNS and DNF files for us to export and send via email to the aid stations.

The QR code just populates to a Google spread sheet that I access, manipulate to be in ascending order by bib numbers. Then in the online software I choose bulk start and choose all runners. I then ‘uncheck’ the ones that don’t show up on the Google sheet and start the race. Next I choose the runners not on the spreadsheet and create a DNS list to send out. Everyone gets a start time of 6 am unless Cody decides to start in batches, then I have to change start times to match." 

Could just import the list to ultra-tracker, and after the RFID station collects the starting athletes, then it sends the list on to adilas to upload. 

Or import both places, and generate a file like the other stations of runners that check in through that point.
