### ISSUE TITLE
Stats View

### ISSUE THREAD

**Issue by rleikis** [barcradio/ultra-tracker#8]
- [x] Investigate table control libraries for the UI  (free-opensource preferred)
- [x] View with table grid
- [x] Sortable grid

Requirements
- Column Headers:  Sequence-Runner#-In Time-Out Time-Notes
- User should be able to sort columns

**Comment by rleikis** [comment]
This requirement seems obsolete. 
- User should be able to quickly reset the view

**Comment by Tibbs327** [comment]
Sort feature works well
Stats that function correctly - Registered, Incoming, In Station, Through Station, leaving open for now to test the DNF and DNS Stats.

I believe we are leaving Errors, warnings, and finished race for later implementation
